version: "3.3"

services:
  redis-master:
    image: redis:3.2
    networks:
      - outside
    hostname: "redis-master"
    deploy:
      placement:
        constraints: [node.labels.host==6]
      replicas: 1

  redis-slave1:
    image: redis:3.2
    networks:
      - outside
    hostname: "redis-slave1"
    command: ["redis-server", "--slaveof", "redis-master", "6379"]
    deploy:
      placement:
        constraints: [node.labels.host==5]
      replicas: 1

  redis-slave2:
    image: redis:3.2
    networks:
      - outside
    hostname: "redis-slave2"
    command: ["redis-server", "--slaveof", "redis-master", "6379"]
    deploy:
      placement:
        constraints: [node.labels.host==4]
      replicas: 1

  sentinel:
    image: sentinel
    networks:
      - outside
    hostname: "sentinel1"
    environment:
      - SENTINEL_DOWN_AFTER:10000
      - SENTINEL_FAILOVER:10000
      - SENTINEL_QUORUM:2
      - MASTER_IP=redis-master
    deploy:
      # placement:
      #   constraints: [node.labels.host==6]
      replicas: 3

networks:
  outside:
    external:
      name: "host"
