version: "3.3"

services:
  redis-master:
    image: redis:3.2
    networks:
      - outside
    hostname: "redis-master"
    deploy:
      placement:
        constraints: [node.labels.host==6]
      replicas: 1

  redis-slave1:
    image: redis:3.2
    networks:
      - outside
    hostname: "redis-slave1"
    depends_on:
      - redis-master
    command: ["redis-server", "--slaveof", "redis-master", "6379"]
    deploy:
      placement:
        constraints: [node.labels.host==5]
      replicas: 1

  redis-slave2:
    image: redis:3.2
    networks:
      - outside
    hostname: "redis-slave2"
    depends_on:
      - redis-master
    command: ["redis-server", "--slaveof", "redis-master", "6379"]
    deploy:
      placement:
        constraints: [node.labels.host==4]
      replicas: 1

  sentinel1:
    image: sentinel
    networks:
      - outside
    hostname: "sentinel1"
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    environment:
      - SENTINEL_DOWN_AFTER:10000
      - SENTINEL_FAILOVER:10000
      - SENTINEL_QUORUM:2
      - MASTER_IP=redis-master
    deploy:
      placement:
        constraints: [node.labels.host==6]
      replicas: 1

  sentinel2:
    image: sentinel
    networks:
      - outside
    hostname: "sentinel2"
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    environment:
      - SENTINEL_DOWN_AFTER:10000
      - SENTINEL_FAILOVER:10000
      - SENTINEL_QUORUM:2
      - MASTER_IP=redis-master
    deploy:
      placement:
        constraints: [node.labels.host==5]
      replicas: 1

  sentinel3:
    image: sentinel
    networks:
      - outside
    hostname: "sentinel3"
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    environment:
      - SENTINEL_DOWN_AFTER:10000
      - SENTINEL_FAILOVER:10000
      - SENTINEL_QUORUM:2
      - MASTER_IP=redis-master
    deploy:
      placement:
        constraints: [node.labels.host==4]
      replicas: 1

networks:
  outside:
    external:
      name: "host"
