version: '3.1'

services:
  kafka1:
    image: hyperledger/fabric-kafka:x86_64-0.4.5
    restart: always
    hostname: kafka1
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=192.168.3.2:2181,192.168.3.2:2182,192.168.3.2:2183

  kafka2:
    image: hyperledger/fabric-kafka:x86_64-0.4.5
    restart: always
    hostname: kafka2
    ports:
      - 9093:9092
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=192.168.3.2:2181,192.168.3.2:2182,192.168.3.2:2183

  kafka3:
    image: hyperledger/fabric-kafka:x86_64-0.4.5
    restart: always
    hostname: kafka3
    ports:
      - 9094:9092
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=192.168.3.2:2181,192.168.3.2:2182,192.168.3.2:2183
